haraka:
  haraka:
    env:
    - name: HARAKA_HOSTLIST
      value: localhost,localhost.kubero.dev
    - name: HARAKA_ME
      value: mynameisnobody
    - name: HARAKA_PLUGINS
      value: helo.checks,mail_from.is_resolvable,rcpt_to.in_host_list,headers,relay_all
    - name: HARAKA_HELO_CHECKS_CHECK
      value: match_re=false,bare_ip=false,dynamic=false,big_company=true,forward_dns=false,rdns_match=false,host_mismatch=false,proto_mismatch=false
    - name: HARAKA_HELO_CHECKS_REJECT
      value: host_mismatch=false,big_company=false,rdns_match=false
    - name: HARAKA_HELO_CHECKS_SKIP
      value: private_ip=false,relaying=true
    - name: HARAKA_LOG_LEVEL
      value: info
    - name: HARAKA_LOG_TIMESTAMP
      value: false
    - name: HARAKA_LOG_FORMAT
      value: default
    - name: HARAKA_RELAY
      value: all
    - name: HARAKA_SMTP_FORWARD
      value: true
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8025
