apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: kuberoprometheus
type: application
version: 0.1.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: "25.20.*"
    condition: prometheus.server.enabled
  - name: alertmanager
    version: "1.10.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.alertmanager.enabled
  - name: kube-state-metrics
    version: "5.18.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: "4.32.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.prometheus-node-exporter.enabled