apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: kuberomysql
type: application
version: 0.1.0

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-mysql
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x