apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuberoapp.fullname" . }}-web
  labels:
    {{- include "kuberoapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  {{- if and (.Values.autoscaling.enabled) (lt (.Values.web.autoscaling.minReplicas | float64) 1.0) }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "kuberoapp.selectorLabels" . | nindent 6 }}-web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kuberoapp.selectorLabels" . | nindent 8 }}-web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kuberoapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.deploymentstrategy "git" }}
      initContainers:
        - name: {{ .Chart.Name }}-fetcher
          securityContext:
            {{- toYaml .Values.image.fetch.securityContext | nindent 12 }}
          image: "{{ .Values.image.fetch.repository }}:{{ .Values.image.fetch.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
            - name: GIT_REPOSITORY
              value: {{ include "kuberoapp.clone_url" . | quote }}
            {{- if .Values.branch }}
            - name: GIT_BRANCH
              value: {{ .Values.branch | quote }}
            {{- end }}
            {{- if .Values.ref }}
            - name: GIT_REF
              value: {{ .Values.ref | quote }}
            {{- end }}
            {{- if .Values.image.build.command }}
            - name: KUBERO_BUILDPACK_DEFAULT_BUILD_CMD
              value: {{ .Values.image.build.command | quote }}
            {{- end }}
            {{- if .Values.image.run.command }}
            - name: KUBERO_BUILDPACK_DEFAULT_RUN_CMD
              value: {{ .Values.image.run.command | quote }}
            {{- end }}
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          volumeMounts:
            - mountPath: /root/.ssh
              name: deployment-keys
              readOnly: true
            - mountPath: /app
              name: app-storage
        - name: {{ .Chart.Name }}-builder
          securityContext:
            {{- toYaml .Values.image.build.securityContext | nindent 12 }}
          image: "{{ .Values.image.build.repository }}:{{ .Values.image.build.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["./init-build.sh"]
          volumeMounts:
            - mountPath: /app
              name: app-storage
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.image.run.securityContext | nindent 12 }}
          {{- if eq .Values.deploymentstrategy "docker" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          {{- else }}
          image: "{{ .Values.image.run.repository }}:{{ .Values.image.run.tag | default "latest" }}"
          workingDir: /app
          command: ["./init-web.sh"]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROC_TYPE
              value: web
            - name: PORT
              value: {{ .Values.image.containerPort | default "8080" | quote }}
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- if eq .Values.deploymentstrategy "git" }}
            - mountPath: /app
              name: app-storage
              {{- if or .Values.image.run.readOnlyAppStorage (not (hasKey .Values.image.run "readOnlyAppStorage")) }}
              readOnly: true
              {{- end }}
            {{- end }}
            - mountPath: /tmp
              name: tmp-storage
              readOnly: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: deployment-keys
        secret:
          defaultMode: 0600
          secretName: deployment-keys
      - name: app-storage
        emptyDir: {}
      - name: tmp-storage
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}