{{- if .Values.vulnerabilityscan -}}
{{- if .Values.vulnerabilityscan.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kuberoapp.fullname" . }}-vuln
spec:
  schedule: {{ .Values.vulnerabilityscan.schedule | default "0 0 * * *" }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- if eq .Values.deploymentstrategy "git" }}
          - name: trivy-repo-scan
            image: {{ .Values.vulnerabilityscan.image.repository }}:{{ .Values.vulnerabilityscan.image.tag | default "latest" }}
            #command: ["trivy",  "repo", "-q", "-f", "json", "--exit-code", "0", "--severity", "HIGH,CRITICAL", "--ignore-unfixed", ""]
            command: ["trivy",  "repo", {{ .Values.gitrepo.homepage | quote }}, "-q", "-f", "json", "--scanners", "vuln,secret,config", "--exit-code", "0"]
          {{- else }}
          - name: trivy-image-scan
            image: {{ .Values.vulnerabilityscan.image.repository }}:{{ .Values.vulnerabilityscan.image.tag | default "latest" }}
            command: ["trivy",  "image", "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}", "-q", "-f", "json", "--scanners", "vuln" "--exit-code", "0"]
          {{- end }}
          restartPolicy: Never
{{- end }}
{{- end }}