{{- if gt (len .Values.basicAuth.accounts) 0 }}
{{- $accounts := .Values.basicAuth.accounts }}
{{- $val := "" }}
{{- range $account := $accounts }}
{{- $val = printf "%s%s\n" $val $account.hash }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuberoapp.fullname" . }}-htpasswd
type: Opaque
data:
  auth: {{ $val | trimSuffix "\n" | b64enc }}
{{- end }}
