{{- if or (eq .Values.buildstrategy "dockerfile") (eq .Values.buildstrategy "nixpacks") }}
{{- $mainnamespace := .Values.mainnamespace | default "kubero" -}}
# retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
{{- $secretObj := (lookup "v1" "Secret" $mainnamespace "registry-login") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $dockerconfigjson := (get $secretData ".dockerconfigjson") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuberoapp.fullname" . }}-pull-secret
type: Opaque
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
---
{{- end }}