{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuberoapp.serviceAccountName" . }}
  labels:
    {{- include "kuberoapp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kuberoapp.serviceAccountName" . }}role
rules:
  - apiGroups: ["application.kubero.dev"]
    resources: ["kuberoapps"]
    verbs: ["update", "patch", "get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kuberoapp.serviceAccountName" . }}rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "kuberoapp.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kuberoapp.serviceAccountName" . }}role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
