# permissions for end users to edit kuberoprometheuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kuberoprometheus-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubero-operator
    app.kubernetes.io/part-of: kubero-operator
    app.kubernetes.io/managed-by: kustomize
  name: kuberoprometheus-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoprometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoprometheuses/status
  verbs:
  - get
