# permissions for end users to edit kuberomemcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberomemcached-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomemcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomemcacheds/status
  verbs:
  - get
