# permissions for end users to edit kuberoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubero-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoes/status
  verbs:
  - get
