# permissions for end users to edit kuberomongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberomongodb-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomongodbs/status
  verbs:
  - get
