# permissions for end users to view kuberoelasticsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberoelasticsearch-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoelasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoelasticsearches/status
  verbs:
  - get
