# permissions for end users to edit kuberopipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberopipeline-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberopipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberopipelines/status
  verbs:
  - get
