# permissions for end users to edit kuberorabbitmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberorabbitmq-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberorabbitmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberorabbitmqs/status
  verbs:
  - get
