# permissions for end users to view kuberoapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberoapp-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoapps/status
  verbs:
  - get
