# permissions for end users to view kuberopostgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberopostgresql-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberopostgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberopostgresqls/status
  verbs:
  - get
