# permissions for end users to view kuberoredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberoredis-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoredis/status
  verbs:
  - get
