# permissions for end users to view kuberoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubero-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoes/status
  verbs:
  - get
