# permissions for end users to edit kuberoapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberoapp-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoapps/status
  verbs:
  - get
