# permissions for end users to view kuberomysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberomysql-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomysqls/status
  verbs:
  - get
