# permissions for end users to view kuberomails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberomail-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomails
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomails/status
  verbs:
  - get
