# permissions for end users to view kuberocouchdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberocouchdb-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberocouchdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberocouchdbs/status
  verbs:
  - get
