# permissions for end users to view kuberomongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberomongodb-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberomongodbs/status
  verbs:
  - get
