# permissions for end users to edit kuberokafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberokafka-editor-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberokafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberokafkas/status
  verbs:
  - get
