apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for application.kubero.dev/v1alpha1, Kind: KuberoApp
##
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "roles"
  - "clusterroles"
  - "clusterrolebindings"
  - "rolebindings"
  verbs:
  - "*"
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoapps
  - kuberoapps/status
  - kuberoapps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - "autoscaling"
  resources:
  - "horizontalpodautoscalers"
- verbs:
  - "*"
  apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - "batch"
  resources:
  - "cronjobs"
#### Addons
- apiGroups:
    - "opstreelabs.in"
  resources:
    - "mongodbs"
  verbs:
    - "*"
- apiGroups:
    - "redis.redis.opstreelabs.in"
  resources:
    - "redis"
    - "redisclusters"
  verbs:
    - "*"
- apiGroups:
    - "postgres-operator.crunchydata.com"
  resources:
    - "postgresclusters"
  verbs:
    - "*"
- apiGroups:
    - "minio.min.io"
  resources:
    - "tenants"
  verbs:
    - "*"
##
## Rules for application.kubero.dev/v1alpha1, Kind: Kubero
##
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoes
  - kuberoes/status
  - kuberoes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  - "persistentvolumeclaims/finalizers"
  - "persistentvolumes/finalizers"
- verbs:
  - "*"
  apiGroups:
  - "operators.coreos.com"
  resources:
  - "clusterserviceversions"

##
## Rules for application.kubero.dev/v1alpha1, Kind: KuberoPipeline
##
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberopipelines
  - kuberopipelines/status
  - kuberopipelines/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "namespaces"
  - "secrets"
#+kubebuilder:scaffold:rules
