# Source: kuberoapp/templates/job-vulnerabilityscan.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: appsmith-repo-scan
spec:
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trivy-repo-scan
            image: aquasec/trivy:latest
            #command: ["trivy",  "repo", "-q", "-f", "json", "--exit-code", "0", "--severity", "HIGH,CRITICAL", "--ignore-unfixed", ""]
            command: ["trivy",  "repo", "https://github.com/foo/bar", "-q", "-f", "json", "--exit-code", "0"]
          restartPolicy: Never