apiVersion: application.kubero.dev/v1alpha1
kind: Kubero
metadata:
  name: kubero-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kubero/values.yaml
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: Always
    repository: ghcr.io/kubero-dev/kubero/kubero
    tag: "main"
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: true
    hosts:
    - host: kubero.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 2000
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  kubero:
    debug: "*.*"
    namespace: kubero
    contenxt: kind-kubero
    context: kind-kubero
    webhook_url: http://localhost:3000/api/webhook
    config: |
      kubero:
        context: kind-kubero
        namespace: kubero
        port: 3000
      podSizeList:
      - name: small
        description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
        default: true
        resources:
          requests:
            memory: 0.5Gi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
      - name: medium
        description: 'Medium (CPU: 1, Memory: 2Gi)'
        resources:
          requests:
            memory: 2Gi
            cpu: 1000m
          limits:
            memory: 4Gi
            cpu: 2000m
      - name: large
        description: 'Large (CPU: 2, Memory: 4Gi)'
        active: false
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m