apiVersion: application.kubero.dev/v1alpha1
kind: KuberoPrometheus
metadata:
  name: kubero-prometheus
spec:
  # Default values copied from <project_dir>/helm-charts/kuberoprometheus/values.yaml
  prometheus:
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    server:
      enabled: true
      ingress:
        enabled: false
        hosts:
          - prometheus.localhost
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false