apiVersion: application.kubero.dev/v1alpha1
kind: KuberoMail
metadata:
  name: kuberomail-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kuberomail/values.yaml
  haraka:
    haraka:
      env:
      - name: HARAKA_HOSTLIST
        value: localhost,localhost.kubero.dev
      - name: HARAKA_ME
        value: mynameisnobody
      - name: HARAKA_PLUGINS
        value: helo.checks,mail_from.is_resolvable,rcpt_to.in_host_list,headers,relay_all
      - name: HARAKA_HELO_CHECKS_CHECK
        value: mynameisnobody
      - name: HARAKA_HELO_CHECKS_REJECT
        value: host_mismatch=false,big_company=false,rdns_match=false
      - name: HARAKA_HELO_CHECKS_SKIP
        value: private_ip=false,relaying=true
      - name: HARAKA_LOG_LEVEL
        value: debug
      - name: HARAKA_LOG_TIMESTAMP
        value: false
      - name: HARAKA_LOG_FORMAT
        value: info

    replicaCount: 1

    service:
      type: ClusterIP
      port: 8025
