apiVersion: application.kubero.dev/v1alpha1
kind: Kubero
metadata:
  name: kubero-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kubero/values.yaml
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: Always
    repository: ghcr.io/kubero-dev/kubero/kubero
    tag: "main"
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: true
    hosts:
    - host: kubero.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 2000
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  kubero:
    debug: ""
    namespace: kubero
    context: kind-kubero
    webhook_url: http://localhost:3000/api/webhook
    config: |
      kubero:
        context: kind-kubero
        namespace: kubero
        port: 3000
      buildpacks:
        - name: NodeJS
          language: JavaScript
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: node
            tag: latest
            command: "npm install"
          run:
            repository: node
            tag: latest
            command: "node index.js"
        - name: PHP
          language: PHP
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: composer
            tag: latest
            command: "composer install; chown -R 1000:1000 /app"
          run:
            repository: webdevops/php-apache
            tag: "8.1"
            readOnlyAppStorage: false
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            command: "apache2-foreground"
        - name: Python
          language: Python
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: python
            tag: 3.10-buster
            command: "python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"
          run:
            repository: python
            tag: 3.10-buster
            command: "python3 -m venv .venv && . .venv/bin/activate && python3 main.py"
        - name: GoLang
          language: GoLang
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: golang
            tag: alpine
            command: "go mod download && go mod verify && go build -v -o app"
          run:
            repository: golang
            tag: alpine
            command: "./app"
        - name: Ruby
          language: Ruby
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: ruby
            tag: "2.7"
            command: "export GEM_HOME=/app/bundle; bundle install --jobs=4 --retry=3"
          run:
            repository: ruby
            tag: "2.7"
            command: "export GEM_HOME=/app/bundle; bundle exec ruby main.rb"
        - name: Static
          language: HTML
          fetch:
            repository: ghcr.io/kubero-dev/buildpacks/fetch
            tag: main
          build:
            repository: busybox
            tag: latest
            command: "echo 'Buildpack not required'"
          run:
            repository: webdevops/nginx
            tag: alpine
            command: "supervisord"
      podSizeList: 
      - name: small
        description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
        default: true
        resources:
          requests:
            memory: 0.5Gi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
      - name: medium
        description: 'Medium (CPU: 1, Memory: 2Gi)'
        resources:
          requests:
            memory: 2Gi
            cpu: 1000m
          limits:
            memory: 4Gi
            cpu: 2000m
      - name: large
        description: 'Large (CPU: 2, Memory: 4Gi)'
        active: false
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m