## Append samples you want in your CSV to this file as resources ##
resources:
- application_v1alpha1_kuberoapp.yaml
- application_v1alpha1_kubero.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
