apiVersion: v2
appVersion: 15.1.0
description: A Helm chart for Kuberos Postgresql
name: kuberopostgresql
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-postgresql
    version: 12.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x