{{- if eq .Values.buildstrategy "kpack" }}
{{- $date := now | date "2006-01-02-150405" }}
{{- $name := printf "%s-%s-%s" .Values.app .Values.pipeline .Values.repository.tag -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    batch.kubernetes.io/job-name: {{ $name }}
    job-name: {{ $name }}
  name: {{ $name }}
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: {{ $name }}
        build: {{ .Values.buildstrategy }}
        job-name: {{ $name }}
    spec:
      containers:
        - env:
          - name: REPOSITORY
            value: {{ .Values.repository.pull }}{{ .Values.repository.image }}
          - name: TAG
            value: {{ .Values.repository.tag }}
          - name: APP
            value: {{ .Values.app }}
          command:
          - sh
          - -c
          - 'kubectl patch kuberoapps $APP --type=merge -p "{\"spec\":{\"image\":{\"repository\":
            \"$REPOSITORY\",\"tag\": \"$TAG\"}}}"'
          image: bitnami/kubectl:latest
          imagePullPolicy: Always
          name: deployer
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      initContainers:
      - image: {{ .Values.kpack.dispatcher }}
        imagePullPolicy: Always
        name: {{ $name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: APP
          value: {{ .Values.app }}
        - name: PIPELINE
          value: {{ .Values.pipeline }}
        - name: REPOSITORY
          value: {{ .Values.repository.push }}{{ .Values.repository.image }}
        - name: TAG
          value: {{ .Values.repository.tag }}
        - name: SERVICE_ACCOUNT
          value: {{ .Values.kpack.serviceAccount }}
        - name: BUILDER
          value: {{ .Values.kpack.builder }}
        - name: GIT_URL
          value: {{ .Values.git.url }}
        - name: GIT_REF
          value: {{ .Values.git.ref }}
        #command:
        #- tail
        #- -f
        #- /dev/null
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kpack-sa
{{- end }}