# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/application.kubero.dev_kuberoapps.yaml
- bases/application.kubero.dev_kuberoes.yaml
- bases/application.kubero.dev_kuberopipelines.yaml
- bases/application.kubero.dev_kuberomysqls.yaml
- bases/application.kubero.dev_kuberopostgresqls.yaml
- bases/application.kubero.dev_kuberoredis.yaml
- bases/application.kubero.dev_kuberomongodbs.yaml
#+kubebuilder:scaffold:crdkustomizeresource
