{{- $mainnamespace := .Values.mainnamespace | default "kubero" -}}
{{- $secretObj := (lookup "v1" "Secret" $mainnamespace "registry-login") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $dockerconfigjson := (get $secretData ".dockerconfigjson") | default "" }}
{{- $registryUsername := (get $secretData "username") | default "" }}
{{- $registryPassword := (get $secretData "password") | default "" }}

{{- $name := .Values.name -}}
{{- $deploymentstrategy := .Values.deploymentstrategy -}}

{{- range .Values.phases }}
{{- if .enabled }}
{{- if and (eq $deploymentstrategy "git") (ne $registryUsername "") }}
apiVersion: v1
kind: Secret
metadata:
  name: kubero-pull-secret
  namespace: {{ $name }}-{{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ $name }}-{{ .name }}
  annotations:
    app.kubernetes.io/comment: "required by trivy to scan the image"
type: Opaque
data:
  username: {{ $registryUsername | quote }}
  password: {{ $registryPassword | quote }}
---
{{- end }}
{{- end }}
{{- end }}