deploymentstrategy: git
mainnamespace: kubero
dockerimage: kubero/template-nodeapp
git:
  repository:
    description: Simple example Node app
    id: 123456789
    name: template-nodeapp
    node_id: R_asdfasdfaa
    owner: kubero-dev
    private: true
    ssh_url: git@github.com:kubero-dev/template-nodeapp.git
  webhook:
    active: true
    created_at: "2022-06-21T19:37:07Z"
    events:
    - pull_request
    - push
    id: 123456789
    insecure: "0"
    url: https://somelocaladress.com/api/github/webhooks
name: dodo
phases:
- context: ""
  enabled: false
  name: review
- context: ""
  enabled: false
  name: test
- context: ""
  enabled: false
  name: stage
- context: kind-kubero
  enabled: true
  name: production
reviewapps: true