# All the values must be consistent and are mandatory!
buildstrategy: "buildpacks" # buildpacks, dockerfile, nixpacks
app: "example"
pipeline: "test"
phase: "test" # not used yet
id: "20240631-2237"
repository: 
  image: "registry-kubero.yourdomain.com/optionalrepositoryowner/pipeline/app"
  tag: "123456" # (optional) defaults to "latest
git:
  url: "git@github.com:kubero-dev/template-nodeapp.git"
  ref: "main"
podSecurityContext:
  fsGroup: 1000

# kpack specific values ar created by Kubero UI. 
buildpack:
  path: "." # path to the app root relative to the repository root
  cnbPlatformApi: "0.13"
dockerfile:
  path: "Dockerfile" # path to the Dockerfile relative to the repository root
  fetcher: 
nixpack:
  path: ".nixpacks/Dockerfile" # path to the Dockerfile relative to the repository root