# All the values must be consistent and are mandatory!
buildstrategy: "nixpacks" # buildpacks, dockerfile, nixpacks
app: "example"
pipeline: "test"
phase: "test" # not used yet
id: "20240631-2237"
repository: 
  image: "registry-kubero.yourdomain.com/optionalrepositoryowner/pipeline/app"
  tag: "123456" # (optional) defaults to "latest
git:
  url: "git@github.com:kubero-dev/template-nodeapp.git"
  ref: "main"
podSecurityContext:
  fsGroup: 1000

# kpack specific values ar created by Kubero UI. 
buildpack:
  cnbPlatformApi: "0.13"
  fetcher: "ghcr.io/kubero-dev/fetch:latest"
  builder: "paketobuildpacks/builder-jammy-full:latest" #List of Builders : https://paketo.io/docs/reference/builders-reference/
dockerfile:
  path: "Dockerfile" # path to the Dockerfile relative to the repository root
  fetcher: "ghcr.io/kubero-dev/fetch:latest"
  pusher: "quay.io/containers/buildah:v1.35"
nixpack:
  path: ".nixpacks/Dockerfile" # path to the Dockerfile relative to the repository root
  fetcher: "ghcr.io/kubero-dev/fetch:latest"
  builder: "ghcr.io/kubero-dev/build:latest"
  pusher: "quay.io/containers/buildah:v1.35"