apiVersion: v2
appVersion: 6.0.3
description: Elasticsearch is a distributed search and analytics engine. It is used for web search, log monitoring, and real-time analytics. Ideal for Big Data applications.
home: https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch
name: kuberoelasticsearch
type: application
version: 0.1.0
dependencies:
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-elasticsearch
    version: 19.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x