apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubero.fullname" . }}
  labels:
    {{- include "kubero.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubero.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubero.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/kubero
              name: kubero-config-volume
          env:
            # TODO: needs some investigation. Crashes with UNABLE_TO_VERIFY_LEAF_SIGNATURE
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: KUBERO_CONTEXT
              value: "{{ .Values.kubero.context }}" 
            - name: KUBERO_NAMESPACE
              value: "{{ .Values.kubero.namespace }}" 
            - name: KUBERO_WEBHOOK_URL
              value: "{{ .Values.kubero.webhook_url }}" 
            - name: KUBERO_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: KUBERO_WEBHOOK_SECRET
            {{- if .Values.kubero.repositories.github.enabled }}
              - name: GITHUB_PERSONAL_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kubero-secrets
                    key: GITHUB_PERSONAL_ACCESS_TOKEN
            {{- end }}
            {{- if .Values.kubero.repositories.gitea.enabled }}
              - name: GITEA_PERSONAL_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kubero-secrets
                    key: GITEA_PERSONAL_ACCESS_TOKEN
            {{- end }}
            {{- if .Values.kubero.repositories.gitlab.enabled }}
              - name: GITLAB_PERSONAL_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kubero-secrets
                    key: GITLAB_PERSONAL_ACCESS_TOKEN
            {{- end }}
            - name: KUBECONFIG_BASE64
              valueFrom:
                  secretKeyRef:
                    name: kubero-secrets
                    key: KUBECONFIG_BASE64
            - name: DEBUG
              value: "{{ .Values.kubero.debug }}" 
            - name: KUBERO_CONFIG_PATH
              value: /etc/kubero/config.yaml
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: GIT_DEPLOYMENTKEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GIT_DEPLOYMENTKEY_PUBLIC
            - name: GIT_DEPLOYMENTKEY_PRIVATE_B64
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GIT_DEPLOYMENTKEY_PRIVATE_B64
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kubero-config-volume
          configMap:
            name: kubero-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
