{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubero.serviceAccountName" . }}
  labels:
    {{- include "kubero.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubero.serviceAccountName" . }}role
rules:
  - apiGroups: ["application.kubero.dev"]
    resources: ["kuberopipelines"]
    verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubero.serviceAccountName" . }}role
rules:
  - apiGroups: ["application.kubero.dev"]
    resources: ["kuberoes"]
    verbs: ["*"]
  - apiGroups: ["application.kubero.dev"]
    resources: ["kuberoapps"]
    verbs: ["*"]
  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["namespaces", "secrets", "pods", "pods/log", "pods/exec", "events", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubero.serviceAccountName" . }}rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "kubero.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kubero.serviceAccountName" . }}role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubero.serviceAccountName" . }}rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "kubero.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubero.serviceAccountName" . }}role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
